server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  server:
    eviction-interval-timer-in-ms: 1 #default 60000
    response-cache-update-interval-ms: 1 #default 30000
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: 127.0.0.1