server:
  port: 82
spring:
  application:
    name: SERVER1
 # h2:
 #   console:
 #     enabled: false
  #    path: /h2-console
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: true
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 1
    instance-id: ${spring.application.name}:${server.port}